# Server
spring.application.name=broker
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gerbitpcb
spring.datasource.username=gerbitpcb
spring.datasource.password=gerbitpcb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-u5hjksq5qzigsdkq.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.gerbitpcb.com