spring.application.name=supplier-murata

server.port=8082

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# Hibernate Auto-generation (Use 'create' just for the first run, then change to 'update')
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true