spring.application.name=supplier-ti

# Server Port (So it doesn't clash with the Broker)
server.port=8081

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/supplier_ti_db
spring.datasource.username=
spring.datasource.password=

# Hibernate Magic (Auto-creates tables based on your Entities)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true