spring.application.name=supplier-ti

server.port=8081

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# Hibernate Auto-generation (Use 'create' just for the first run, then change to 'update')
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true